In [1]:
# 1D arrays:

In [2]:
import numpy as np

In [4]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [5]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [6]:
# Check the type of the array

type(a)

numpy.ndarray

In [7]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int32')

In [6]:
# Create a numpy array

b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

In [7]:
# Check the type of array

type(b)

numpy.ndarray

In [8]:
# Check the value type

b.dtype

dtype('float64')

In [9]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [12]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [13]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [14]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [13]:
# Create the index list

select = [0, 2, 3]

In [14]:
# Use List to select elements

d = c[select]
d

array([20,  2,  3])

In [18]:
# Assign the specified elements to new value

c[select] = 100000
c

array([100000,      1, 100000, 100000,      4])

In [51]:
# Create a numpy array

a = np.array([[0, 1, 2, 3],[1,2,3,4]])
a

array([[0, 1, 2, 3],
       [1, 2, 3, 4]])

In [52]:
# Get the size of numpy array

a.size

8

In [53]:
# Get the shape/size of numpy array

a.shape

(2, 4)

In [54]:
a.ndim # Returns the dimension of the np array.

2

In [57]:
# reshape() changes the dimension.

a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [1, 2],
       [3, 4]])

In [58]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [62]:
# Get the mean of numpy array

mean = a.mean()
mean

0.0

In [61]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

1.0

In [24]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [25]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

5

In [26]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

-1

In [27]:
# Array Addition:

In [28]:
u = np.array([1, 0])
v = np.array([0, 1])

# Numpy Array Addition

z = u + v
z

array([1, 1])

In [31]:
# Array Multiplication:

In [32]:
y = np.array([1, 2])

# Numpy Array Multiplication

z = 2 * y
z

array([2, 4])

In [33]:
u = np.array([1, 2])
v = np.array([3, 2])

# Calculate the production of two numpy arrays

z = u * v
z

array([3, 4])

In [35]:
# Dot Product:

In [36]:
# Calculate the dot product

np.dot(u, v)

7

In [38]:
# Add the constant to array

u = np.array([1, 2, 3, -1]) 

u + 1

array([2, 3, 4, 0])

In [39]:
# Mathematical Functions:

In [40]:
# The value of pi

np.pi

3.141592653589793

In [41]:
# Create the numpy array in radians

x = np.array([0, np.pi/2 , np.pi])

In [42]:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [43]:
# Linspace:

In [44]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

In [45]:
# Makeup a numpy array within [-2, 2] and 9 elements

np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [46]:
# Makeup a numpy array within [0, 2π] and 100 elements 

x = np.linspace(0, 2*np.pi, num=100)

In [49]:
# Calculate the sine of x list

y = np.sin(x)
y

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [50]:
# 2D Numpy in Python:

In [52]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [53]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [66]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [55]:
# Show the numpy array dimensions

A.ndim

2

In [56]:
# Show the numpy array shape

A.shape

(3, 3)

In [57]:
# Show the numpy array size

A.size

9

In [67]:
# Access the element on the second row and third column

A[1, 2]

23

In [69]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [70]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

In [66]:
X = np.array([[1, 0], [0, 1]]) 
Y = np.array([[2, 1], [1, 2]]) 

# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [67]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [68]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [69]:
# Calculate the dot product

Z = np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])

In [76]:
# Calculate the sine of Z

np.sin(Z)

array([[0.90929743, 0.84147098],
       [0.84147098, 0.90929743]])

In [78]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [79]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [7]:
a = np.arange(24)
a.ndim

1

In [8]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
# Reshaping a array:

b = a.reshape(6,4,1)
b

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

In [12]:
b.itemsize

4

In [90]:
C = np.array([[1,1,1],[2,2,2]])

In [95]:
# axis: if axis = 1 then row wise, if axis = 0 then column wise.

#Example:

C.sum(axis = 0)

array([3, 3, 3])

In [96]:
C.sum(axis = 1)

array([3, 6])

In [100]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
B = np.array([[3,2,1],[6,5,4]])
B

array([[3, 2, 1],
       [6, 5, 4]])

In [103]:
np.cross(A,B)  # Cross product

array([[ -4,   8,  -4],
       [-10,  20, -10]])

In [105]:
A.dot(B.T)  # Dot prod of A and B transpose

array([[10, 28],
       [28, 73]])

In [106]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [108]:
len(dir(np))

618

In [118]:
# sort()

np.sort(B)

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
np.sort(B,axis = 0)

array([[3, 2, 1],
       [6, 5, 4]])

In [121]:
%%time
np.sort(B,axis = 1)

Wall time: 0 ns


array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
%%time
np.sort(B, axis = 1, kind = 'quicksort') # we can mention the kind of sort. 

Wall time: 0 ns


array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
# argsort(): It gives the indices of elements in ascending order.

A.argsort()  # or np.argsort(A)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [132]:
np.argsort(A)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [133]:
np.argsort(A,axis = 0)

array([[0, 0, 0],
       [1, 1, 1]], dtype=int64)

In [134]:
A.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)